
server:
  port: 8093
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: root
    password: 'root'
  h2:
    console:
      settings:
        web-allow-others: true
      enabled: true

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true


#
#
#
#
#server:
#  port: 8093
#spring:
#  application:
#    name: "card"
#  datasource:
#    url: jdbc:mysql://${DB_HOST:localhost}:3306/card
#    username: root
#    password: root
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  jpa:
#    hibernate:
#      ddl-auto: update
