spring:
  application:
    name: "gatewayserver"
  config:
    import: "optional:configserver:http://localhost:8072/"
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true
  info:
    env:
      enabled: true

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

info:
  app:
    name: "gatewayserver"
    description: "Keto Bank gatewayserver Application"
    version: "1.0.0"