spring:
  application:
    name: "gatewayserver"
  config:
    import: "optional:configserver:http://localhost:8072/"
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true #accept lowercase in request
      httpclient:
        connect-timeout: 1000
        response-timeout: 2s
  data:
    redis:
      host: localhost
      port: 6379
      connect-timeout: 2s
      timeout: 1s



management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true
  info:
    env:
      enabled: true

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

info:
  app:
    name: "gatewayserver"
    description: "Keto Bank gatewayserver Application"
    version: "1.0.0"



logging:
  level:
    com:
      keto:
        gatewayserver: DEBUG


resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 2
      waitDurationInOpenState: 10000
      failureRateThreshold: 50

