server:
  port: 8091
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: root
    password: 'root'
  h2:
    console:
      settings:
        web-allow-others: true
      enabled: true

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  config:
    import:
      - "application_prod.yml"
      - "application_qa.yml"
  profiles:
    active: "prod"


build:
  version: "1.0.2"



account:
  message: "Hello from Account microservice"
  name: "Kiransing bhat"
  company: "TCS"
  contact:
    - 8999025679
    - 7447674794
  city: "Latur"



#server:
#  port: 8091
#spring:
#  application:
#    name: "account"
#  datasource:
#    url: jdbc:mysql://${DB_HOST:localhost}:3306/account
#    username: root
#    password: root
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  jpa:
#    hibernate:
#      ddl-auto: update
